const defineDict = <T extends Record<string, Record<string, string>>>(dict: T): { [S in keyof T]: { [K in keyof T[S]]: string } } => dict;

export const ru = defineDict({
  common: {tons: 'т',  cancel: 'Отмена', done: 'Готово', delete: 'Удалить', kg: 'кг', seconds: 'с', minutes: 'мин', activeShort: 'акт', bodyweight: 'вес тела', day: 'День', exercise: 'упражнение', exercises: '{count} упражнений', sets: '{count} подходов', set: 'Подход {count}', start: 'Старт', continue: 'Продолжить', pause: 'Пауза', reasonOptional: 'Причина необязательна' },
  home: {streakValue: '{count} дн',  title: 'Погнали, Вугар', todayPlan: 'Сегодня по плану', active: 'Тренировка идёт', paused: 'Тренировка на паузе', activeMeta: 'День {day} — {name} · упражнение {current} из {total}', planTitle: 'День {day} — {name}', planMeta: '{count} упражнений · ~{minutes} мин', emptyPlan: 'Добавьте первый день в разделе «Тренировки».', workouts: 'тренировок', totalVolume: 'общий объём', supplementStreak: 'стрик добавок', lastWorkout: 'Последняя тренировка' },
  tabs: { home: 'Главная', workouts: 'Тренировки', supplements: 'Добавки', history: 'История', settings: 'Настройки' },
  workouts: { title: 'Тренировки', editPlan: 'Ред. план', alreadyStarted: 'Тренировка уже начата', returnToWorkout: 'Вернуться к тренировке', empty: 'План пуст. Добавьте тренировочный день в редакторе.', selectedDay: 'Выбранный день', startDay: 'Начать день {day}' },
  history: { title: 'История', empty: 'Завершённые тренировки появятся здесь.', detailsMissing: 'Детализация подходов не сохранена для этой старой сессии.', pauses: 'Паузы', pauseOne: 'пауза', pauseFew: 'паузы', endedEarly: 'раньше', skipped: 'пропущено', chartTitle: 'Объём за 8 недель', pauseCount: '{count} {form}' },
  supplements: { title: 'Добавки', today: 'Сегодня', stock: 'Склад', progress: 'Прогресс', schedule: 'Расписание', streak: '{count} дн подряд', lowStock: '{count} добавки заканчиваются — пора докупить', months: '~{count} мес', days: '~{count} дн', stockHint: 'Нажмите +30 у нужной добавки, чтобы пополнить остаток.', daysInRow: 'дней подряд', record: 'Рекорд — {record} дня · до рекорда {remaining}', adherence: '{value}% приёма', complete: 'всё принято', partial: 'частично', ahead: 'впереди', add: '+ Добавка', nameLabel: 'Название добавки', doseLabel: 'Доза добавки', morning: 'Утро', preWorkout: 'Перед трен.', evening: 'Вечер', weekdays: 'Пн|Вт|Ср|Чт|Пт|Сб|Вс' },
  settings: {name:'Вугар', title: 'Настройки', profile: 'с апреля 2026 · {count} тренировок', language: 'Язык', theme: 'Тема', light: 'Светлая', dark: 'Тёмная', workoutReminder: 'Напоминание о тренировке', workoutReminderHint: 'в дни по плану, 18:00', supplementReminder: 'Напоминание о добавках', supplementReminderHint: 'утро · перед трен. · вечер', restSound: 'Звук rest-таймера', restSoundHint: 'сигнал «пора начинать подход»', preSignal: 'Предупредить заранее', preSignalHint: 'тихий сигнал за {seconds} с до конца отдыха', preSignalOff: 'Выкл', export: 'Экспорт данных', showOnboarding: 'Показать подсказки снова', reset: 'Сбросить все данные', resetTitle: 'Сбросить все данные?', resetMessage: 'История и отметки приёма будут удалены. План, добавки и настройки вернутся к исходным.', exportUnavailable: 'Системный share-sheet недоступен на этом устройстве.', exportError: 'Не удалось экспортировать данные: {message}' },
  session: { finishTitle: 'Завершить тренировку?', finishMessage: 'Сделанные подходы будут сохранены, остальные упражнения отмечены как пропущенные.', keepTraining: 'Продолжить тренировку', noActiveTitle: 'Нет активной тренировки', noActiveText: 'Выберите день плана, чтобы начать сессию.', toWorkouts: 'К тренировкам', pauseAction: 'Поставить тренировку на паузу', muscleCore: 'Кор', muscleExercise: 'Упражнение', workingWeight: 'Рабочий вес', reps: '{count} повт', ready: 'Готово', skip: 'Пропустить', skipHint: 'объём не идёт', endEarly: 'Закончить раньше', credited: '{done} из {total} засчитаны', finish: 'Завершить тренировку', skipExercise: 'Пропустить упражнение', rest: 'Отдых', untilSet: 'до подхода {count}', startNow: 'Начать сейчас', restHint: 'В конце — звуковой и тактильный сигнал «пора начинать»', pauseDescription: 'Активное время заморожено — пауза\nне войдёт в итоговое активное время', activeTime: 'Активное', pausedTime: 'На паузе', reasonLabel: 'Причина — необязательно', completed: 'Тренировка завершена', total: 'Всего', volume: 'Объём', vsPrevious: '{value}% к прошлой', endedEarlyStatus: 'закончил раньше', reasonTired: 'Устал', reasonDistracted: 'Отвлёкся', reasonNoTime: 'Не хватило времени', reasonDiscomfort: 'Дискомфорт' },
  planEditor: { deleteTitle: 'Удалить тренировочный день?', deleteMessage: 'Упражнения этого дня тоже будут удалены.', back: '‹ Тренировки', title: 'Редактор плана', dayName: 'Название дня {count}', exerciseName: 'Название упражнения', muscleGroup: 'Группа мышц', edit: 'Ред.', collapse: 'Сверн.', sets: 'Подходы', time: 'Время, с', reps: 'Повторы', weight: 'Вес, кг', timed: 'На время', timedHint: 'На время (без веса)', addExercise: '+ Упражнение', deleteDay: 'Удалить день', addDay: '+ Тренировочный день' },
  onboarding: {
    label: 'Важные подсказки', skip: 'Пропустить', next: 'Далее', done: 'Понятно',
    restTitle: 'Отдых и пауза — разное',
    restBody: 'Rest отсчитывает время между подходами и в конце подаёт звуковой сигнал. Пауза доступна в любой момент и замораживает активное время — перекур не испортит статистику.',
    skipTitle: 'Пропустить или закончить раньше',
    skipBody: 'При пропуске упражнение не идёт в объём. При раннем завершении сделанные подходы засчитываются, а причину — устал, отвлёкся, не хватило времени или дискомфорт — можно оставить как метку в истории.',
    supplementsTitle: 'Добавки — не просто список',
    supplementsBody: 'Отмечай приём утром, перед тренировкой и вечером. Склад считает остаток и предупредит, когда пора докупить, а стрик покажет, сколько дней подряд всё принято.',
    ownTitle: 'Всё под себя',
    ownBody: 'План, упражнения и добавки можно менять целиком. Стартовые названия следуют за языком, а твои остаются твоими; данные хранятся только на телефоне, экспорт JSON — в настройках.',
  },
  seed: {
    dayChestTriceps: 'Грудь и трицепс', dayBackBiceps: 'Спина и бицепс', dayLegs: 'Ноги', dayShouldersAbs: 'Плечи и пресс',
    exerciseBenchPress: 'Жим лёжа', exerciseInclineDumbbellPress: 'Жим гантелей на наклонной', exerciseDumbbellFlyes: 'Разводка гантелей', exerciseCloseGripBenchPress: 'Жим узким хватом', exerciseCablePushdown: 'Разгибание на блоке', exerciseFrenchPress: 'Французский жим', exercisePullUps: 'Подтягивания', exerciseBentOverBarbellRow: 'Тяга штанги в наклоне', exerciseLatPulldown: 'Тяга верхнего блока', exerciseBarbellCurl: 'Подъём штанги на бицепс', exerciseHammerCurl: 'Молотки', exercisePlank: 'Планка', exerciseSquat: 'Приседания', exerciseLegPress: 'Жим ногами', exerciseLegExtension: 'Разгибание ног', exerciseLegCurl: 'Сгибание ног', exerciseCalfRaise: 'Подъём на носки', exerciseOverheadPress: 'Жим над головой', exerciseLateralRaise: 'Разведение гантелей', exerciseRearDelt: 'Задняя дельта', exerciseCrunch: 'Скручивания', exerciseSidePlank: 'Боковая планка',
    muscleChest: 'Грудь', muscleTriceps: 'Трицепс', muscleBack: 'Спина', muscleBiceps: 'Бицепс', muscleCore: 'Кор', muscleLegs: 'Ноги', muscleCalves: 'Икры', muscleShoulders: 'Плечи', muscleAbs: 'Пресс',
    supplementVitaminD3: 'Витамин D3', supplementOmega3: 'Омега-3', supplementCreatine: 'Креатин', supplementCaffeine: 'Кофеин', supplementMagnesium: 'Магний', supplementZinc: 'Цинк',
    doseVitaminD3: '2000 МЕ', doseOmega3: '2 капс', doseCreatine: '5 г', doseCaffeine: '200 мг', doseMagnesium: '400 мг', doseZinc: '25 мг',
    stockUnitCapsules: 'капс', stockUnitServings: 'порции', stockUnitTablets: 'табл',
  },
  notFound: { title: 'Экран не найден', home: 'На главную' },
});
